apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment
  template:
    metadata:
      labels:
        app: appointment
    spec:
      initContainers:
      - name: init-myservice
        image: busybox
        command: ['sh', '-c', 'echo init container initializing && sleep 5']
      containers:
      - name: appointment-app
        image: 877786395093.dkr.ecr.ap-south-1.amazonaws.com/appointment-service:latest
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /appointments
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /appointments
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
